# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle files instead.

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not inherit from the library's dependencies,
# thereby reducing the size of the R class in the final APK.
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Suppress SDK version warnings
android.suppressUnsupportedCompileSdk=34
